config/routes.rb
Rails.application.routes.draw do

  get("/static/faq", { :controller => "static", :action => "faq"})

  get("/static/about", { :controller => "static", :action => "about"})

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get("reviewed_batches", { :controller => "reviews", :action => "reviewed"})

  get("/mirrors/input", { :controller => "mirrors", :action => "input_form"})

  get("/match_brew", { :controller => "unis", :action => "match_num"})

  post("batches/:id/generate_uniques", { :controller => "batches", :action => "generate_uniques"})

  post("batches/:id/generate_unis", { :controller => "batches", :action => "generate_unis"})

  resources :unis

  resources :mirrors

  resources :uniques

  resources :reviews

  resources :batches

  resources :recipes

  resources :styles

  devise_for :users

  devise_scope :user do
    root "devise/registrations#edit"
  end

end

app/models/unique.rb
class Unique < ActiveRecord::Base
  belongs_to :batch
  belongs_to :user
  # belongs_to :mirror

  # has_many :mirrors

  validates :rand_num, :presence => true
  validates :batch, :presence => true
end

app/controllers/uniques_controller.rb
class UniquesController < ApplicationController
  before_action :set_unique, only: [:show, :edit, :update, :destroy]

  # GET /uniques
  # GET /uniques.json
  # Displays the Uniques
  def index
  # Display only the current user's uniques
    # @unique = Unique.new(unique_params)
    # @unique.user = current_user

      if current_user.present?
          @uniques = current_user.uniques
        else
        @uniques = Unique.all
      end
      # @uniques = Unique.all
  end

  # def generate_rand_num
  #   @unique = Unique.new

  #   @unique.rand_num = SecureRandom.random_number(1000000000)
  # end

  def input_form
  #   @match = Unique.find_by({ :rand_num => params("match_unique_num")} )
  end

  def match_num
    @mirror = Mirror.new
    @mirror.mrand_num = params[:new_number]

    @mirror.save

    # @m = Mirror.find_by({ :mrand_num => params[:new_number] })
    @u = Unique.find_by({ :rand_num => params[:new_number] })
    @u = Unique.find_by_rand_num(params[:new_number])
  end

  # GET /uniques/1
  # GET /uniques/1.json
  def show
  end

  # GET /uniques/new
  # def new
  #   @unique = Unique.new
  # end

  # GET /uniques/1/edit
  def edit
  end

  # def generate_uniques
  #   params[:unique_num].to_i.times do Unique.create(batch_id: params[:id], rand_num: rand(1000000))
  #     @unique = Unique.new(unique_params)

  #       respond_to do |format|
  #         if @unique.save
  #           format.html { redirect_to @unique, notice: 'Unique was successfully created.' }
  #           format.json { render :show, status: :created, location: @unique }
  #           else
  #           format.html { render :new }
  #           format.json { render json: @unique.errors, status: :unprocessable_entity }
  #       end
  #     end
  #   end
  #   redirect_to uniques_url(@unique), notice: "Your unqiue numbers are listed below ;]"
  # end

  # POST /uniques
  # POST /uniques.json
  # def create
  #   @unique = Unique.new(unique_params)
  #   @unique.user = current_user

  #   respond_to do |format|
  #     if @unique.save
  #       format.html { redirect_to @unique, notice: 'Unique was successfully created.' }
  #       format.json { render :show, status: :created, location: @unique }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @unique.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /uniques/1
  # PATCH/PUT /uniques/1.json
  def update
    respond_to do |format|
      if @unique.update(unique_params)
        format.html { redirect_to @unique, notice: 'Unique was successfully updated.' }
        format.json { render :show, status: :ok, location: @unique }
      else
        format.html { render :edit }
        format.json { render json: @unique.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uniques/1
  # DELETE /uniques/1.json
  def destroy
    @unique.destroy
    respond_to do |format|
      format.html { redirect_to uniques_url, notice: 'Unique was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unique
      @unique = Unique.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unique_params
      params.require(:unique).permit(:rand_num, :batch_id)
    end
end

app/helpers/uniques_helper.rb
module UniquesHelper
end

app/views/uniques/_form.html.erb
<%= simple_form_for(@unique) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :rand_num %>
    <%= f.association :batch, collection: Batch.all %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<!-- Q: How do we set simple _form_for up so that foreign keys come through in layers and not just at the model level?  -->

<!-- f.association :company, collection: Company.active.all(order: 'name'), prompt: "Choose a Company" -->

app/views/uniques/edit.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Unique #<%= @unique.id %></h3>
      </div>
      <div class="panel-body">
        <%= render 'form', unique: @unique %>
      </div>
    </div>
  </div>
</div>

app/views/uniques/index.html.erb
<div class="page-header">
  <h1>
    Your Unique IDs
    <% if current_user.email == "p1@example.com" %>
    <%= link_to icon('plus'), new_unique_path, class: "btn btn-lg btn-success" %>
    <% end %>
  </h1>
  <h5>Brewers - Apply the unique number that corresponds to the batch you're sharing. Write it on the bottle of beer, or on the cap, the label or where ever your fan can see it.  Your fans will come back to the site, input the number, access the brew's profile and review it.</h5>
</div>

<!-- Responsive, Isotope-based layout example -->

<!-- <div class="row">
  <div class="col-xs-12  text-center">
  <%#= paginate(@uniques) %>
  </div>
</div> -->

<div class="panel panel-default">
  <div class="panel-heading">UNIQUE NUMBERS CREATED</div>

    <table class="table" align="left">
      <thead>
          <tr>
              <th>ID#</th>
              <th>Image/Label</th>
              <th>Brew Date</th>
              <th>Recipe Name</th>
              <th>Unique Number</th>
              <% if current_user.email == "p1@example.com" %>
              <th>User ID</th>
              <th>Controls</th>
              <% end %>
          </tr>
      </thead>
      <tbody>
      <% @uniques.each do |unique| %>


          <tr>
            <td><%= unique.id %></td>
            <td><%= image_tag unique.batch.image, :height => '50px', :width => '50px' %></td>
            <td><%= unique.batch.brew_date %></td>
            <td><%= unique.batch.recipe.name %></td>
            <td><%= unique.rand_num %></td>

          <% if current_user.email == "p1@example.com" %>
            <td><%= unique.batch.user_id %></td>
            <td>

              <%= link_to icon('search-plus'), unique, class: "btn btn-primary" %>

              <%= link_to icon('edit'), edit_unique_url(unique), class: "btn btn-warning" %>

              <%= link_to icon('trash-o'), unique, method: :delete, data: { confirm: "Do you really want to delete this unique?" }, class: "btn btn-danger" %>
          <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
</div>


<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container');

    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/uniques/input_form.html.erb
<h1>Find your brew to leave a review</h1>


<form action="http://localhost:3000/uniques/match">
    <div>
      <label for="first" >Input Brew Number</label>
      <input name="new_number" type="text" id="first">
      <input align="right" type="submit" value="Find your brew">
    </div>
  </form>

app/views/uniques/match_num.html.erb
<% if @u.present? %>
  <h1 align="center">We have a match!!<span aria-hidden="true" class="fa fa-beer"></span></h1> <h2 align="center">You've made a match for brew ID#: <%= @u.rand_num %></h2>

  <div class="row">
  <!-- <div class="col-lg-6">
    <h1 align="right">Review this brew! <%#= link_to icon('plus'), new_review_path( :batch_id => @u.batch_id ), class: "btn btn-lg btn-success" %></h1>
  </div> -->

  <div class="col-lg-12">
  <div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Batch ID#<%= @u.batch_id %> | <%= @u.batch.recipe.name %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12 col-lg-12">
            <dl class="dl-horizontal">
              <!-- <dt>Recipe: </dt> -->
              <dd><%#= @u.batch.recipe.name %></dd>

              <dt>The Brewer: </dt>
              <dd><%= image_tag @u.batch.user.avatar, :class => "img-responsive" %></dd>
              <dd><%= @u.batch.recipe.user.username %></dd>

              <dt>Brew date: </dt>
              <dd><%= @u.batch.brew_date %></dd>

              <dt>Bottle date: </dt>
              <dd><%= @u.batch.bottle_date %></dd>

              <dt>Actual Original Graavity: </dt>
              <dd><%= @u.batch.aog %></dd>

              <dt>Final Gravity: </dt>
              <dd><%= @u.batch.afg %></dd>

              <dt>ABV: </dt>
              <dd><%= @u.batch.aabv %>%</dd>

              <dt>Aroma: </dt>
              <dd><%= @u.batch.aaroma %></dd>

              <dt>IBUs: </dt>
              <dd><%= @u.batch.aibu %></dd>

              <dt></dt>
              <dd><%= image_tag @u.batch.image, :class => "img-responsive" %></dd>

              <dt>Description: </dt>
              <dd><%= @u.batch.aflavpro %></dd>

<hr>          <!-- Creates a new review from an existing batch -->
              <h1 align="left">Review this brew!<%= link_to icon('plus'), new_review_path( :batch_id => @u.batch_id ), class: "btn btn-lg btn-success" %></h1>
            </dl>

              </div> <!-- end div column -->
            </div> <!-- end div row -->
          </div> <!-- end div panel body -->
      </div> <!-- end div class panel -->
    </div> <!-- end div col offset -->
  </div> <!-- end div row -->
</div> <!-- end div col-lg-6 -->


  <%#= form_tag("/batches/#{params[:id]}/post_new_review", method:"post") do %>
  <!-- <%#= form_tag("/reviews/#{params[:id]}/post_new_review", method:"post") do %> -->
        <!-- <input align="right" type="submit" value="Submit Review"> -->
      <!-- </div> -->
  <%# end %>

<% else %>
  <h1>Awwwwww Man!<span aria-hidden="true" class="fa fa-frown-o"></span></h1>
<%= params[:new_number] %> doesn't match any of the brews in our database. Please click on <%= link_to "Rate-a-Brew", "/mirrors/input" %> and try again!
<% end %>

app/views/uniques/new.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">New Unique</h3>
      </div>
      <div class="panel-body">
        <%= render 'form', unique: @unique %>
      </div>
    </div>
  </div>
</div>

app/views/uniques/show.html.erb
<!-- Responsive panel example-->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Unique #<%= @unique.id %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <dl class="dl-horizontal">
              <dt>Rand num</dt>
              <dd><%= @unique.rand_num %></dd>

              <dt>Batch</dt>
              <dd><%= @unique.batch_id %></dd>

              <dt>User ID</dt>
              <dd><%#= @unique.user_id %></dd>

              <dt>Image</dt>
              <dd><%= image_tag @unique.batch.image, :height => '25%', :width => '25%'  %></dd>

            </dl>
            <div class="btn-group btn-group-justified">
              <%= link_to icon('chevron-left'), uniques_path, class: "btn btn-primary" %>

              <%= link_to icon('edit'), edit_unique_path(@unique), class: "btn btn-warning" %>

              <%= link_to icon('trash-o'), @unique, method: :delete, data: { confirm: "Do you really want to delete this unique?" }, class: "btn btn-danger" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->