config/routes.rb
Rails.application.routes.draw do

  get("/static/faq", { :controller => "static", :action => "faq"})

  get("/static/about", { :controller => "static", :action => "about"})

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get("reviewed_batches", { :controller => "reviews", :action => "reviewed"})

  get("/mirrors/input", { :controller => "mirrors", :action => "input_form"})

  get("/match_brew", { :controller => "unis", :action => "match_num"})

  post("batches/:id/generate_uniques", { :controller => "batches", :action => "generate_uniques"})

  post("batches/:id/generate_unis", { :controller => "batches", :action => "generate_unis"})

  resources :unis

  resources :mirrors

  resources :uniques

  resources :reviews

  resources :batches

  resources :recipes

  resources :styles

  devise_for :users

  devise_scope :user do
    root "devise/registrations#edit"
  end

end

app/models/uni.rb
class Uni < ActiveRecord::Base
  belongs_to :batch
  belongs_to :user
end

app/controllers/unis_controller.rb
class UnisController < ApplicationController
  before_action :set_uni, only: [:show, :edit, :update, :destroy]


  # GET /unis
  # GET /unis.json
  def index
    if current_user.present?
        @unis = current_user.unis
      else
      @unis = Uni.all
    end
  end

  # GET /unis/1
  # GET /unis/1.json
  def show
  end

  # GET /unis/new
  def new
    @uni = Uni.new
  end

  # GET /unis/1/edit
  def edit
  end

  def match_num
    @u = Uni.find_by({ :rand_num => params[:new_number] })
  end

  # POST /unis
  # POST /unis.json
  def create
    @uni = Uni.new(uni_params)

    @uni.user = current_user

      respond_to do |format|
        if @uni.save
          format.html { redirect_to @uni, notice: 'Uni was successfully created.' }
          format.json { render :show, status: :created, location: @uni }
        else
          format.html { render :new }
          format.json { render json: @uni.errors, status: :unprocessable_entity }
        end
      end
    end

  # PATCH/PUT /unis/1
  # PATCH/PUT /unis/1.json
  def update
    respond_to do |format|
      if @uni.update(uni_params)
        format.html { redirect_to @uni, notice: 'Uni was successfully updated.' }
        format.json { render :show, status: :ok, location: @uni }
      else
        format.html { render :edit }
        format.json { render json: @uni.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unis/1
  # DELETE /unis/1.json
  def destroy
    @uni.destroy
    respond_to do |format|
      format.html { redirect_to unis_url, notice: 'Uni was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uni
      @uni = Uni.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def uni_params
      params.require(:uni).permit(:rand_num, :batch_id)
    end
end

app/helpers/unis_helper.rb
module UnisHelper
end

app/views/unis/_form.html.erb
<%= simple_form_for(@uni) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :rand_num %>
    <%= f.association :batch %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/unis/edit.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Uni #<%= @uni.id %></h3>
      </div>
      <div class="panel-body">
        <%= render 'form', uni: @uni %>
      </div>
    </div>
  </div>
</div>

app/views/unis/index.html.erb
<div class="page-header">
  <h1>
    Your unique Brew IDs
    <% if current_user.email == "p1@example.com" %>
    <%= link_to icon('plus'), new_uni_path, class: "btn btn-lg btn-success" %>
    <% end %>
  </h1>
  <h5>Brewers - Apply the number that corresponds to the batch you're sharing. Write it on the bottle of beer, or on the cap, the label or where ever your fans can see it.  They'll come back to the site, input the number, access the brew's profile and review the beer! Each review will then be accessible to you.</h5>
</div>

<!-- Responsive, Isotope-based layout example -->

<!-- <div class="row">
  <div class="col-xs-12  text-center">
  <%#= paginate(@unis) %>
  </div>
</div> -->

<div class="panel panel-caution">
  <div class="panel-heading">GENERATED NUMBERS</div>

    <table class="table" align="left">
      <thead>
          <tr>
              <th>ID#</th>
              <th>Image/Label</th>
              <th>Brew Date</th>
              <th>Recipe Name</th>
              <th>uni Number</th>
            <% if current_user.email == "p1@example.com" %>
              <th>User ID</th>
              <th>Controls</th>
              <% end %>
          </tr>
      </thead>
      <tbody>
      <% @unis.each do |uni| %>
          <tr>
            <td><%= uni.id %></td>
            <td><%= image_tag uni.batch.image, :height => '50px', :width => '50px' %></td>
            <td><%= uni.batch.brew_date %></td>
            <td><%= uni.batch.recipe.name %></td>
            <td><%= uni.rand_num %></td>

          <% if current_user.email == "p1@example.com" %>
            <td><%= uni.batch.user_id %></td>
            <td>

              <%= link_to icon('search-plus'), uni, class: "btn btn-primary" %>

              <%= link_to icon('edit'), edit_uni_url(uni), class: "btn btn-warning" %>

              <%= link_to icon('trash-o'), uni, method: :delete, data: { confirm: "Do you really want to delete this uni?" }, class: "btn btn-danger" %>
          <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
</div>


<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container');

    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/unis/match_num.html.erb
<div class="page-header">

<%# if @x.present? %>
 <%# @u.rand_num != params[:new_number] %>
<!-- <h1 align="center">A number cannot be used more than once.</h1> -->
<%# else %>

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
  <% if @u.present? %>
    <h1 align="center">We have a match!<span aria-hidden="true" class="fa fa-beer"></span></h1> <h2 align="center"><%#= @u.rand_num %> Here's what you have in your hand:</h2>
  </div>
  Incoming Params of new_number: <%= params[:new_number]%>
  <% @u.batch.matched = params[:new_number]%>
  <% @u.batch.save %>
</div>

  <div class="row">
  <div class="col-lg-12">
  <div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Batch ID#<%= @u.batch_id %> | <%= @u.batch.recipe.name %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12 col-lg-12">
            <dl class="dl-horizontal">

              <dt>The Brewer: </dt>
              <dd><%= image_tag @u.batch.user.avatar, :height => "100px", :width => "100px", :class => "img-responsive" %></dd>
              <dd><%= @u.batch.recipe.user.username %></dd>

              <dt>Brew date: </dt>
              <dd><%= @u.batch.brew_date %></dd>

              <dt>Bottle date: </dt>
              <dd><%= @u.batch.bottle_date %></dd>

              <dt>Actual Original Graavity: </dt>
              <dd><%= @u.batch.aog %></dd>

              <dt>Final Gravity: </dt>
              <dd><%= @u.batch.afg %></dd>

              <dt>ABV: </dt>
              <dd><%= @u.batch.aabv %>%</dd>

              <dt>Aroma: </dt>
              <dd><%= @u.batch.aaroma %></dd>

              <dt>IBUs: </dt>
              <dd><%= @u.batch.aibu %></dd>

              <dt></dt>
              <dd><%= image_tag @u.batch.image, :height => "100px", :width => "100px" %></dd>

              <dt>Description: </dt>
              <dd><%= @u.batch.aflavpro %></dd>

              <%# Uni.find_by({ :batch_id => 'batch.id', :batch_id => 'review.batch_id' }) %>


<hr>          <!-- Creates a new review from an existing batch -->

          <% if @u.is_used == true %>
                <h1 align="center">Ooops!</h1>
                <h4 align="center">Something went wrong. Please try a different number.</h4>

                  <form action="/match_brew">
                    <div align="center">
                      <label for="new number" >Input Brew Number</label>
                      <input name="new_number" type="text" id="first">
                      <input align="right" type="submit" value="Find your brew">
                    </div>
                  </form>

          <% else %>

              <p><h4 align="center">Tell the brewer what you <u>really</u> think about this brew.</h4></p>
              <p><h4 align="center">Review it now.</h4></p>
              <p align ="center"><%= link_to icon('check'), new_review_path( :batch_id => (@u.batch_id) ), class: "btn btn-lg btn-success" %></p>
              <!-- Send batch info to the new review path; send params[:new_number] to the edit_batch_path -->

              <% @u.is_used = true %>
              <% @u.save %>

          <% end %>

            </dl>

                </div> <!-- end div column -->
              </div> <!-- end div row -->
            </div> <!-- end div panel body -->
        </div> <!-- end div class panel -->
      </div> <!-- end div col offset -->
    </div> <!-- end div row -->
  </div> <!-- end div col-lg-6 -->
</div> <!-- end div row -->


<% else %>
  <h1>Wait. What!?<span aria-hidden="true" class="fa fa-frown-o"></span></h1>
<%= params[:new_number] %> doesn't match with any of the brews in our database. Please click on <%= link_to "Rate-a-Brew", "/mirrors/input" %> and try again!
<% end %>
<%# end %>

</div>

app/views/unis/new.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">New Uni</h3>
      </div>
      <div class="panel-body">
        <%= render 'form', uni: @uni %>
      </div>
    </div>
  </div>
</div>

app/views/unis/show.html.erb
<!-- Responsive panel example-->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Uni #<%= @uni.id %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <dl class="dl-horizontal">
              <dt>Rand num</dt>
              <dd><%= @uni.rand_num %></dd>

              <dt>Batch</dt>
              <dd><%= @uni.batch_id %></dd>

              <dt>User</dt>
              <dd><%= @uni.user_id %></dd>

            </dl>
            <div class="btn-group btn-group-justified">
              <%= link_to icon('chevron-left'), unis_path, class: "btn btn-primary" %>

              <%= link_to icon('edit'), edit_uni_path(@uni), class: "btn btn-warning" %>

              <%= link_to icon('trash-o'), @uni, method: :delete, data: { confirm: "Do you really want to delete this uni?" }, class: "btn btn-danger" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->