config/routes.rb
Rails.application.routes.draw do

  get("/static/faq", { :controller => "static", :action => "faq"})

  get("/static/about", { :controller => "static", :action => "about"})

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get("reviewed_batches", { :controller => "reviews", :action => "reviewed"})

  get("/mirrors/input", { :controller => "mirrors", :action => "input_form"})

  get("/match_brew", { :controller => "unis", :action => "match_num"})

  post("batches/:id/generate_uniques", { :controller => "batches", :action => "generate_uniques"})

  post("batches/:id/generate_unis", { :controller => "batches", :action => "generate_unis"})

  resources :unis

  resources :mirrors

  resources :uniques

  resources :reviews

  resources :batches

  resources :recipes

  resources :styles

  devise_for :users

  devise_scope :user do
    root "devise/registrations#edit"
  end

end

app/models/style.rb
class Style < ActiveRecord::Base
  has_many :recipes

  validates :name, :presence => true
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :set_style, only: [:show]
  skip_before_action :authenticate_user!

  # GET /styles
  # GET /styles.json
  def index
    # @styles = Style.order("name ASC").page(params[:page]).per(7)
    @styles = Style.order("name ASC")
  end

  # GET /styles/1
  # GET /styles/1.json
  def show
  end

  # GET /styles/new
  def new
    @style = Style.new
  end

  # GET /styles/1/edit
  def edit
  end

  # POST /styles
  # POST /styles.json
  def create
    @style = Style.new(style_params)

    respond_to do |format|
      if @style.save
        format.html { redirect_to @style, notice: 'Style was successfully created.' }
        format.json { render :show, status: :created, location: @style }
      else
        format.html { render :new }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /styles/1
  # PATCH/PUT /styles/1.json
  def update
    respond_to do |format|
      if @style.update(style_params)
        format.html { redirect_to @style, notice: 'Style was successfully updated.' }
        format.json { render :show, status: :ok, location: @style }
      else
        format.html { render :edit }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /styles/1
  # DELETE /styles/1.json
  def destroy
    # @style.destroy
    # respond_to do |format|
    #   format.html { redirect_to styles_url, notice: 'Style was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_style
      @style = Style.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def style_params
      params.require(:style).permit(:name, :std_flavor_profile, :com_ex_image)
    end
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/_form.html.erb
<%= simple_form_for(:style) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :std_flavor_profile %>
    <%= f.input :com_ex_image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/styles/edit.html.erb
<div class="page-header">
  <div class="row">
    <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Style: <%= @style.name %></h3>
        </div>
        <div class="panel-body">
          <%= render 'form', style: @style %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/styles/index.html.erb
<div class="page-header">
<div class="row">
  <h1>
    Beer Styles
    <%# if current_user.email == "p1@example.com" %>
      <%#= link_to icon('plus'), new_style_path, class: "btn btn-lg btn-success" %>
    <%# end %>
  </h1>
  <h5>
    The BJCP style guidelines currently recognize <%= Style.count %> different, distinct, individual and judgeable styles of beer (ales and lagers). Check out the flavor profiles of some of the more popular and widely distributed brands we've included here.  Brewers, use this as your inspiration when planning the 'perfect' recipe.
  </h5>
  </div>
</div>

<!-- Search Div Top -->
<!-- <div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Beer Styles (start typing)" class="form-control">
  </div>
</div> -->

<!-- Div Paginate Top -->
<!-- <div class="row">
  <div class="col-xs-12  text-center">
  <%#= paginate(@styles) %>
  </div>
</div> -->

<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading"></div>
      <div class="row isotope-container">
        <div class="col-xs-12">

            <table class="table" align="left">
              <thead>
                  <tr><b>
                      <th>Name</th>
                      <th>ID#</th>
                      <th>Example</th>
                      <th>Flavor Profile</th>
                      <th>More</th>
                  </tr></b>
              </thead>

              <tbody>
                <div class="row container">
                  <% @styles.each do |style| %>
                      <tr>
                        <td><%= style.name %></td>
                        <td><%= style.id %></td>
                        <td><%= image_tag style.com_ex_image, :height => '100px', :width => '100px', :class => "img-circle"  %></td>
                        <td width="50%"><font size="3px"><%= style.std_flavor_profile.truncate(120, omission: '...')  %></font></td>
                        <td width="5%">
                          <div class="btn-group btn-group-justified">
                                <%= link_to icon('search-plus'), style, class: "btn btn-primary" %>
                          </div></td>
                        <td width="5%">
                        <%# if current_user.email == "philmaclin@gmail.com" %>
                            <%#= link_to icon('trash-o'), @style, method: :destroy, data: { confirm: "Do you really want to delete this style?" }, class: "btn btn-danger" %>
                            <%# else %>
                        <%# end %>
                        </td>
                      </tr>
                  <% end %>
                </div> <!-- end div container -->
              </tbody>
            </table>

        </div> <!-- div col xs 12 -->
      </div> <!-- div row isotope container-->
  </div> <!-- div panel panel-default -->
</div> <!-- end div container -->


<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container');

    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/styles/new.html.erb
<div class="page-header">
  <div class="row">
    <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">New Style</h3>
        </div>
        <div class="panel-body">
          <%= render 'form', style: @style %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/styles/old_style_index.html.erb
<div class="page-header">
  <h1>
    Beer Styles
    <%# if current_user.email == "p1@example.com" %>
      <%#= link_to icon('plus'), new_style_path, class: "btn btn-lg btn-success" %>
    <%# end %>
  </h1>
  <h5>
    The BJCP style guidelines currently recognize <%= Style.count %> different, distinct, individual and judgeable styles of beer (ales and lagers). Check out the flavor profiles of some of the more popular and widely distributed brands we've included here.  Brewers, use this as your inspiration when planning the 'perfect' recipe.
  </h5>
</div>

<!-- Responsive, Isotope-based layout example -->

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Beer Styles (start typing)" class="form-control">
  </div>
</div>

<div class="row">
  <div class="col-xs-12  text-center">
  <%= paginate(@styles) %>
  </div>
</div>

<div class="row isotope-container">
<% @styles.each do |style| %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-6 isotope-item">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><%= style.name %></h3>
      </div>
      <div class="panel-body">
        <dl>
          <dt>Flavor Profile:</dt>
          <dd><%= style.std_flavor_profile %></dd>
          <hr>
          <dt>Commercial Example:</dt>
          <dd><%= image_tag style.com_ex_image, :height => '50%', :width => '50%', :class => "img-circle"  %></dd>

        </dl>

          <div class="btn-group btn-group-justified">
              <%= link_to icon('search-plus'), style, class: "btn btn-primary" %>
            <%# if current_user.email == "p1@example.com" %>
              <%#= link_to icon('edit'), edit_style_url(style), class: "btn btn-warning" %>
              <%#= link_to icon('trash-o'), style, method: :delete, data: { confirm: "Do you really want to delete this style?" }, class: "btn btn-danger" %>
          <%# end %>

        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container');

    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/styles/show.html.erb
<!-- Responsive panel example-->
<div class="page-header">
<div class="row">
<div class="row-height">
</div>
  <div class="row">
    <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Style: <%= @style.name %></h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-12">
              <dl class="dl-horizontal">
                <dt>Flavor profile:</dt>
                <dd><%= @style.std_flavor_profile %></dd>

                <dt></dt>
                <dd><%= image_tag @style.com_ex_image, :height => '65%', :width => '65%'   %></dd>

              </dl>
              <div class="btn-group btn-group-justified">
                <%= link_to icon('chevron-left'), styles_path, class: "btn btn-primary" %>
                  <%# if current_user.email == "philmaclin@gmail.com" %>

                    <%#= link_to icon('edit'), edit_style_path(@style), class: "btn btn-warning" %>

                    <%#= link_to icon('trash-o'), @style, method: :delete, data: { confirm: "Do you really want to delete this style?" }, class: "btn btn-danger" %>

                  <%# end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>
<!-- End responsive panel example -->