config/routes.rb
Rails.application.routes.draw do

  get("/static/faq", { :controller => "static", :action => "faq"})

  get("/static/about", { :controller => "static", :action => "about"})

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get("reviewed_batches", { :controller => "reviews", :action => "reviewed"})

  get("/mirrors/input", { :controller => "mirrors", :action => "input_form"})

  get("/match_brew", { :controller => "unis", :action => "match_num"})

  post("batches/:id/generate_uniques", { :controller => "batches", :action => "generate_uniques"})

  post("batches/:id/generate_unis", { :controller => "batches", :action => "generate_unis"})

  resources :unis

  resources :mirrors

  resources :uniques

  resources :reviews

  resources :batches

  resources :recipes

  resources :styles

  devise_for :users

  devise_scope :user do
    root "devise/registrations#edit"
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/batch.rb
class Batch < ActiveRecord::Base

  mount_uploader :image, ImageUploader

  belongs_to :user
  belongs_to :recipe

  has_many :reviews
  has_many :uniques
  has_many :unis

  validates :brew_date, :presence => true
  validates :bottle_date, :presence => true
  validates :recipe_id, :presence => true

end

app/models/mirror.rb
class Mirror < ActiveRecord::Base
  belongs_to :unique

  has_many :uniques

  validates :mrand_num, :presence => true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  belongs_to :style

  has_many :batches

  # Do we validate user or user_id, the foreign key?
 validates :user, :presence => true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :batch

  # validates :overall_rating, :presence => true
  # validates :user, :presence => true
  # validates :batch, :presence => true
  validates :matched, :uniqueness => true

  # validates_uniqueness_of :new_number
  # validates_uniqueness_of :matched
end

app/models/style.rb
class Style < ActiveRecord::Base
  has_many :recipes

  validates :name, :presence => true
end

app/models/uni.rb
class Uni < ActiveRecord::Base
  belongs_to :batch
  belongs_to :user
end

app/models/unique.rb
class Unique < ActiveRecord::Base
  belongs_to :batch
  belongs_to :user
  # belongs_to :mirror

  # has_many :mirrors

  validates :rand_num, :presence => true
  validates :batch, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base

  mount_uploader :avatar, AvatarUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recipes
  has_many :batches
  has_many :reviews
  has_many :uniques
  has_many :unis


end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  skip_before_action :authenticate_user!

  def faq
  end

  def about
  end

end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :set_style, only: [:show]
  skip_before_action :authenticate_user!

  # GET /styles
  # GET /styles.json
  def index
    # @styles = Style.order("name ASC").page(params[:page]).per(7)
    @styles = Style.order("name ASC")
  end

  # GET /styles/1
  # GET /styles/1.json
  def show
  end

  # GET /styles/new
  def new
    @style = Style.new
  end

  # GET /styles/1/edit
  def edit
  end

  # POST /styles
  # POST /styles.json
  def create
    @style = Style.new(style_params)

    respond_to do |format|
      if @style.save
        format.html { redirect_to @style, notice: 'Style was successfully created.' }
        format.json { render :show, status: :created, location: @style }
      else
        format.html { render :new }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /styles/1
  # PATCH/PUT /styles/1.json
  def update
    respond_to do |format|
      if @style.update(style_params)
        format.html { redirect_to @style, notice: 'Style was successfully updated.' }
        format.json { render :show, status: :ok, location: @style }
      else
        format.html { render :edit }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /styles/1
  # DELETE /styles/1.json
  def destroy
    # @style.destroy
    # respond_to do |format|
    #   format.html { redirect_to styles_url, notice: 'Style was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_style
      @style = Style.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def style_params
      params.require(:style).permit(:name, :std_flavor_profile, :com_ex_image)
    end
end

app/controllers/unis_controller.rb
class UnisController < ApplicationController
  before_action :set_uni, only: [:show, :edit, :update, :destroy]


  # GET /unis
  # GET /unis.json
  def index
    if current_user.present?
        @unis = current_user.unis
      else
      @unis = Uni.all
    end
  end

  # GET /unis/1
  # GET /unis/1.json
  def show
  end

  # GET /unis/new
  def new
    @uni = Uni.new
  end

  # GET /unis/1/edit
  def edit
  end

  def match_num
    @u = Uni.find_by({ :rand_num => params[:new_number] })
  end

  # POST /unis
  # POST /unis.json
  def create
    @uni = Uni.new(uni_params)

    @uni.user = current_user

      respond_to do |format|
        if @uni.save
          format.html { redirect_to @uni, notice: 'Uni was successfully created.' }
          format.json { render :show, status: :created, location: @uni }
        else
          format.html { render :new }
          format.json { render json: @uni.errors, status: :unprocessable_entity }
        end
      end
    end

  # PATCH/PUT /unis/1
  # PATCH/PUT /unis/1.json
  def update
    respond_to do |format|
      if @uni.update(uni_params)
        format.html { redirect_to @uni, notice: 'Uni was successfully updated.' }
        format.json { render :show, status: :ok, location: @uni }
      else
        format.html { render :edit }
        format.json { render json: @uni.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unis/1
  # DELETE /unis/1.json
  def destroy
    @uni.destroy
    respond_to do |format|
      format.html { redirect_to unis_url, notice: 'Uni was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uni
      @uni = Uni.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def uni_params
      params.require(:uni).permit(:rand_num, :batch_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/helpers/mirrors_helper.rb
module MirrorsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/uniques_helper.rb
module UniquesHelper
end

app/helpers/unis_helper.rb
module UnisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dobrew</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body { padding-top: 70px; }>
     <div class="page-header">

      <nav class="navbar navbar-default navbar-fixed-top">
        <!-- <a class="navbar-brand" href="#"><img alt="TBE" <%#= image_tag "TBE_Logo_transExported_35x34.png", :height => '100%', :width => '100%' %></a> -->

        <div class="container-fluid" >
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><%= link_to "Home", root_url %></li>
              <li><%= link_to "Popular Beer Styles", styles_path %></li>
              <li><%= link_to "Recipes", recipes_path %></li>
              <li><%= link_to "Batches", batches_path %></li>
              <li><%= link_to "Reviews", reviews_path %></li>
              <li><%#= link_to "MyUnique Numbers", uniques_path %></li>
              <li><%#= link_to "MyBrew IDs", unis_path %></li>
              <li><%#= link_to "Mirrors", mirrors_path %></li>
              <li><%= link_to "Rate-a-Brew", "/mirrors/input" %></li>
              <li><%= link_to "FAQs", "/static/faq" %></li>
              <li><%= link_to "About", "/static/about" %></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
              <% if current_user.present? %>
                <li><%= link_to current_user.username, edit_user_registration_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, :method => "delete" %></li>
              <% else  %>
                <li><%= link_to "Sign In", new_user_session_path %></li>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <% end %>
            </ul>

            <div class="form-group">
              <form class="navbar-form navbar-left" action="/match_brew">
                <div align="left">
                  <font color="white"><label for="new number" ></label></font>
                  <!-- <input name="new_number" type="text" id="first" class="form-control span5" placeholder="Enter Unique #"> -->
                  <input name="new_number" type="text" id="first" class="form-control span" size="10" placeholder="Brew No." >
                  <input align="right" type="submit" class="form-control span" value="Find your brew">
                </div>
              </form>
            </div> <!-- end form group -->

          </div><!-- /.navbar-collapse -->

        </div><!-- /.container-fluid -->
      </nav>

<div class="container"> <!-- lower -->
   <script src="js/bootstrap.min.js"></script>
    <% if alert.present? %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= alert %>
</div> <!-- end lower container? -->
      <% end %>

<% if notice.present? %>
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
<% end %>

  <%= yield %>
    </div> <!-- end header -->
  </div> <!-- end page header -->

  </body>
</html>